import { FONT, S } from "../common/theme";

export const STATIC_STYLES = {
  ...S,
  wrapper: {
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 160px)",
    fontFamily: FONT,
  },
  standaloneHeading: {
    textAlign: "center",
    background: "linear-gradient(180deg, #ffffff 40%, #cbd5e1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    fontSize: "2.2rem",
    fontWeight: "700",
    margin: "40px 0 28px 0",
    letterSpacing: "-0.03em",
    lineHeight: "1.2",
    flexShrink: 0,
  },
  idleContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    background: "rgba(255,255,255,0.02)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "24px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
    overflow: "hidden",
    boxSizing: "border-box",
    padding: "24px",
    animation: "expandIn 0.5s cubic-bezier(0.25, 1, 0.5, 1) forwards",
  },
  chatHistory: {
    flex: 1,
    overflowY: "auto",
    paddingRight: "8px",
    marginBottom: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255,255,255,0.1) transparent",
  },
  bubbleAi: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    color: "#e2e8f0",
    padding: "12px 16px",
    borderRadius: "18px 18px 18px 4px",
    maxWidth: "80%",
    fontSize: "0.95rem",
    lineHeight: "1.5",
    border: "1px solid rgba(255,255,255,0.03)",
  },
  dockArea: { position: "relative", width: "100%", flexShrink: 0 },
  idleInputWrap: {
    width: "100%",
    position: "relative",
    animation: "fadeUp 0.4s ease forwards",
  },
  previewArea: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    padding: "16px 16px 4px 16px",
  },
  inputRow: {
    display: "flex",
    alignItems: "center",
    padding: "6px 8px 6px 16px",
    gap: "12px",
  },
  previewCard: {
    position: "relative",
    width: "72px",
    height: "72px",
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  previewImage: { width: "100%", height: "100%", objectFit: "cover" },
  fileIconBadge: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "4px",
  },
  fileExtensionText: {
    fontSize: "0.6rem",
    fontWeight: "bold",
    color: "#94a3b8",
  },
  previewCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    background: "linear-gradient(to top, rgba(0,0,0,0.8), transparent)",
    padding: "4px",
    display: "flex",
    alignItems: "center",
  },
  previewNameText: {
    fontSize: "0.55rem",
    color: "#cbd5e1",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    width: "100%",
  },
  closePreviewButton: {
    position: "absolute",
    top: "4px",
    right: "4px",
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    backgroundColor: "#1c1c24",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "#fff",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  textInput: {
    flexGrow: 1,
    background: "none",
    border: "none",
    color: "#fff",
    outline: "none",
    fontSize: "0.95rem",
    fontFamily: FONT,
    lineHeight: "1.5",
    padding: "2px 0",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 12px",
    fontSize: "0.9rem",
    cursor: "pointer",
    borderRadius: "9px",
  },
  iconSvg: {
    width: "16px",
    height: "16px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "2",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  editTextarea: {
    width: "100%",
    minHeight: "44px",
    maxHeight: "200px",
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(168,85,247,0.5)",
    borderRadius: "12px",
    color: "#fff",
    fontFamily: FONT,
    fontSize: "0.95rem",
    lineHeight: "1.5",
    padding: "10px 12px",
    resize: "none",
    outline: "none",
    boxSizing: "border-box",
  },
  editActionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    marginTop: "6px",
  },
  editButton: {
    padding: "6px 14px",
    borderRadius: "10px",
    fontSize: "0.8rem",
    fontWeight: "500",
    cursor: "pointer",
    border: "1px solid rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.06)",
    color: "#e2e8f0",
  },
  editButtonPrimary: {
    padding: "6px 14px",
    borderRadius: "10px",
    fontSize: "0.8rem",
    fontWeight: "500",
    cursor: "pointer",
    border: "1px solid rgba(255,255,255,0.15)",
    background: "linear-gradient(135deg, #3d1060 0%, #6b1045 100%)",
    color: "#ffffff",
  },
  editTriggerButton: {
    background: "none",
    border: "none",
    color: "#94a3b8",
    fontSize: "0.75rem",
    cursor: "pointer",
    padding: "2px 4px",
    opacity: 0.7,
  },
};

export const createAssistantStyles = ({
  inputFocused,
  plusHover,
  sendHover,
  isMobile = false,
}) => ({
  ...STATIC_STYLES,
  ...(isMobile
    ? {
        wrapper: {
          ...STATIC_STYLES.wrapper,
          height: "calc(100svh - 154px)",
          minHeight: "500px",
          alignItems: "center",
          justifyContent: "center",
          paddingBottom: "36px",
          boxSizing: "border-box",
        },
        standaloneHeading: {
          ...STATIC_STYLES.standaloneHeading,
          width: "100%",
          maxWidth: "360px",
          alignSelf: "center",
          textAlign: "center",
          fontSize: "clamp(1.72rem, 7.8vw, 2.08rem)",
          margin: "0 auto 42px auto",
          padding: "0 8px",
          lineHeight: "1.24",
          boxSizing: "border-box",
        },
        idleContainer: {
          ...STATIC_STYLES.idleContainer,
          flex: "0 0 auto",
          width: "100%",
          justifyContent: "center",
          paddingTop: "0",
          paddingBottom: "0",
        },
        idleInputWrap: {
          ...STATIC_STYLES.idleInputWrap,
          maxWidth: "100%",
          margin: "0 auto",
          padding: "0 2px",
          alignSelf: "center",
          boxSizing: "border-box",
        },
        card: {
          ...STATIC_STYLES.card,
          padding: "14px",
          borderRadius: "22px",
          marginTop: "14px",
          minHeight: "calc(100svh - 186px)",
        },
        chatHistory: {
          ...STATIC_STYLES.chatHistory,
          paddingRight: 0,
          marginBottom: "12px",
          gap: "12px",
        },
        bubbleAi: {
          ...STATIC_STYLES.bubbleAi,
          maxWidth: "92%",
          fontSize: "0.92rem",
          lineHeight: "1.58",
        },
        userBubbleContainer: {
          maxWidth: "90%",
        },
        inputRow: {
          ...STATIC_STYLES.inputRow,
          minHeight: "72px",
          padding: "12px 10px 12px 14px",
          gap: "12px",
        },
        textInput: {
          ...STATIC_STYLES.textInput,
          fontSize: "1rem",
          lineHeight: "1.45",
        },
        textareaMinHeight: "38px",
        previewArea: {
          ...STATIC_STYLES.previewArea,
          padding: "12px 12px 2px 12px",
        },
      }
    : {}),
  unifiedForm: {
    display: "flex",
    flexDirection: "column",
    background: "rgba(255,255,255,0.04)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: inputFocused
      ? "1px solid rgba(168,85,247,0.5)"
      : "1px solid rgba(255,255,255,0.12)",
    boxShadow: inputFocused ? "0 0 0 4px rgba(168,85,247,0.12)" : "none",
    transition:
      "border-radius 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease",
    overflow: "hidden",
    ...(isMobile
      ? {
          borderRadius: "34px",
          background: "rgba(255,255,255,0.052)",
        }
      : {}),
  },
  plusButton: {
    width: isMobile ? "42px" : "32px",
    height: isMobile ? "42px" : "32px",
    borderRadius: "50%",
    background: plusHover
      ? "linear-gradient(135deg, #4d1478 0%, #7d1456 100%)"
      : "linear-gradient(135deg, #3d1060 0%, #6b1045 100%)",
    color: "#ffffff",
    border: "1px solid rgba(255,255,255,0.15)",
    fontSize: "1.4rem",
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.2s ease, transform 0.15s ease",
    transform: plusHover ? "scale(1.06)" : "scale(1)",
  },
  sendButton: {
    width: isMobile ? "44px" : "40px",
    height: isMobile ? "44px" : "40px",
    borderRadius: "50%",
    background: sendHover
      ? "linear-gradient(135deg, #4d1478 0%, #7d1456 100%)"
      : "linear-gradient(135deg, #3d1060 0%, #6b1045 100%)",
    border: "1px solid rgba(255,255,255,0.15)",
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition:
      "background 0.2s ease, transform 0.15s ease, box-shadow 0.2s ease",
    transform: sendHover ? "scale(1.06)" : "scale(1)",
    boxShadow: sendHover ? "0 4px 16px rgba(125,20,86,0.5)" : "none",
  },
  stopButton: {
    width: isMobile ? "44px" : "40px",
    height: isMobile ? "44px" : "40px",
    borderRadius: "50%",
    background: sendHover
      ? "linear-gradient(135deg, #9a1f3d 0%, #c0282e 100%)"
      : "linear-gradient(135deg, #7d1830 0%, #a3201f 100%)",
    border: "1px solid rgba(255,255,255,0.15)",
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition:
      "background 0.2s ease, transform 0.15s ease, box-shadow 0.2s ease",
    transform: sendHover ? "scale(1.06)" : "scale(1)",
    boxShadow: sendHover ? "0 4px 16px rgba(163,32,31,0.5)" : "none",
  },
});
