export const FONT =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
export const CHAR_LIMIT = 300;

export const S = {
  icon: {
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "2",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  thumbCard: {
    width: "130px",
    height: "130px",
    borderRadius: "18px",
    overflow: "hidden",
    background: "linear-gradient(135deg, #3d1060 0%, #6b1045 100%)",
    flexShrink: 0,
    boxShadow: "0 4px 15px rgba(80,10,80,0.3)",
    cursor: "pointer",
  },
  thumbImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  thumbFileInner: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  thumbFileExt: {
    fontSize: "0.75rem",
    fontWeight: "700",
    color: "rgba(255,255,255,0.9)",
    letterSpacing: "0.05em",
  },
  bubbleAi: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.06)",
    color: "#e2e8f0",
    padding: "14px 20px",
    borderRadius: "4px 18px 18px 18px",
    maxWidth: "75%",
    fontSize: "0.95rem",
    lineHeight: "1.6",
  },
  bubbleUser: {
    background: "linear-gradient(135deg, #3d1060 0%, #6b1045 100%)",
    color: "#fff",
    padding: "14px 20px",
    borderRadius: "18px 18px 4px 18px",
    fontSize: "0.95rem",
    lineHeight: "1.6",
    boxShadow: "0 4px 15px rgba(80,10,80,0.3)",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  // --- PAST PAPERS VIEWER STYLES ---
  viewerHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#3b1e54",
    padding: "12px 20px",
    borderTopLeftRadius: "12px",
    borderTopRightRadius: "12px",
    borderBottom: "1px solid #1a1a1a",
  },
  viewerTitle: {
    color: "#d8b4fe",
    fontSize: "14px",
    fontWeight: "500",
  },
  viewerControls: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  toggleContainer: {
    display: "flex",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderRadius: "8px",
    padding: "4px",
  },
  toggleBtn: {
    backgroundColor: "transparent",
    color: "#a1a1aa",
    border: "none",
    padding: "6px 16px",
    fontSize: "14px",
    fontWeight: "600",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
  },
  toggleBtnActive: {
    backgroundColor: "#6b21a8",
    color: "#ffffff",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  downloadBtn: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "transparent",
    color: "#d8b4fe",
    border: "1px solid #6b21a8",
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background 0.2s",
  },
};
